set_property -dict [list \
  CONFIG.PSU_BANK_0_IO_STANDARD {LVCMOS18} \
  CONFIG.PSU_BANK_1_IO_STANDARD {LVCMOS18} \
  CONFIG.PSU_BANK_2_IO_STANDARD {LVCMOS18} \
  CONFIG.PSU_DDR_RAM_HIGHADDR {0x1FFFFFFFF} \
  CONFIG.PSU_DDR_RAM_HIGHADDR_OFFSET {0x800000000} \
  CONFIG.PSU_DDR_RAM_LOWADDR_OFFSET {0x80000000} \
  CONFIG.PSU_MIO_31_DRIVE_STRENGTH {12} \
  CONFIG.PSU_MIO_31_SLEW {fast} \
  CONFIG.PSU_MIO_44_PULLUPDOWN {pullup} \
  CONFIG.PSU_MIO_4_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_TREE_PERIPHERALS {Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash##Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad SPI Flash#Quad\
I Flash#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#SD 0#I2C 1#I2C 1######PCIE###UART 0#UART 0########SD 1#SD 1#SD 1#SD 1#SD 1#SD 1#SD 1#SD 1#SD 1#Gem 2#Gem 2#Gem 2#Gem 2#Gem 2#Gem 2#Gem 2#Gem\
Gem 2#Gem 2#Gem 2#Gem 2#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#USB 1#MDIO 2#MDIO 2} \
  CONFIG.PSU_MIO_TREE_SIGNALS {sclk_out#miso_mo1#mo2#mo3#mosi_mi0#n_ss_out##n_ss_out_upper#mo_upper[0]#mo_upper[1]#mo_upper[2]#mo_upper[3]#sclk_out_upper#sdio0_data_out[0]#sdio0_data_out[1]#sdio0_data_out[2]#sdio0_data_out[3]#sdio0_data_out[4]#sdio0_data_out[5]#sdio0_data_out[6]#sdio0_data_out[7]#sdio0_cmd_out#sdio0_clk_out#sdio0_bus_pow#scl_out#sda_out######reset_n###rxd#txd########sdio1_bus_pow#sdio1_wp#sdio1_cd_n#sdio1_data_out[0]#sdio1_data_out[1]#sdio1_data_out[2]#sdio1_data_out[3]#sdio1_cmd_out#sdio1_clk_out#rgmii_tx_clk#rgmii_txd[0]#rgmii_txd[1]#rgmii_txd[2]#rgmii_txd[3]#rgmii_tx_ctl#rgmii_rx_clk#rgmii_rxd[0]#rgmii_rxd[1]#rgmii_rxd[2]#rgmii_rxd[3]#rgmii_rx_ctl#ulpi_clk_in#ulpi_dir#ulpi_tx_data[2]#ulpi_nxt#ulpi_tx_data[0]#ulpi_tx_data[1]#ulpi_stp#ulpi_tx_data[3]#ulpi_tx_data[4]#ulpi_tx_data[5]#ulpi_tx_data[6]#ulpi_tx_data[7]#gem2_mdc#gem2_mdio_out}\
  CONFIG.PSU__DDRC__BG_ADDR_COUNT {2} \
  CONFIG.PSU__DDRC__BRC_MAPPING {ROW_BANK_COL} \
  CONFIG.PSU__DDRC__BUS_WIDTH {64 Bit} \
  CONFIG.PSU__DDRC__CL {17} \
  CONFIG.PSU__DDRC__CLOCK_STOP_EN {0} \
  CONFIG.PSU__DDRC__COMPONENTS {Components} \
  CONFIG.PSU__DDRC__CWL {16} \
  CONFIG.PSU__DDRC__DDR4_ADDR_MAPPING {1} \
  CONFIG.PSU__DDRC__DDR4_CAL_MODE_ENABLE {0} \
  CONFIG.PSU__DDRC__DDR4_CRC_CONTROL {0} \
  CONFIG.PSU__DDRC__DDR4_MAXPWR_SAVING_EN {0} \
  CONFIG.PSU__DDRC__DDR4_T_REF_MODE {0} \
  CONFIG.PSU__DDRC__DDR4_T_REF_RANGE {Normal (0-85)} \
  CONFIG.PSU__DDRC__DEVICE_CAPACITY {8192 MBits} \
  CONFIG.PSU__DDRC__DM_DBI {DM_NO_DBI} \
  CONFIG.PSU__DDRC__DRAM_WIDTH {8 Bits} \
  CONFIG.PSU__DDRC__ECC {Disabled} \
  CONFIG.PSU__DDRC__ECC_SCRUB {0} \
  CONFIG.PSU__DDRC__ENABLE {1} \
  CONFIG.PSU__DDRC__ENABLE_2T_TIMING {0} \
  CONFIG.PSU__DDRC__ENABLE_DP_SWITCH {0} \
  CONFIG.PSU__DDRC__EN_2ND_CLK {0} \
  CONFIG.PSU__DDRC__FGRM {1X} \
  CONFIG.PSU__DDRC__FREQ_MHZ {1} \
  CONFIG.PSU__DDRC__LPDDR3_DUALRANK_SDP {0} \
  CONFIG.PSU__DDRC__LP_ASR {manual normal} \
  CONFIG.PSU__DDRC__MEMORY_TYPE {DDR 4} \
  CONFIG.PSU__DDRC__PARITY_ENABLE {0} \
  CONFIG.PSU__DDRC__PER_BANK_REFRESH {0} \
  CONFIG.PSU__DDRC__PHY_DBI_MODE {0} \
  CONFIG.PSU__DDRC__PLL_BYPASS {0} \
  CONFIG.PSU__DDRC__PWR_DOWN_EN {0} \
  CONFIG.PSU__DDRC__RANK_ADDR_COUNT {0} \
  CONFIG.PSU__DDRC__RD_DQS_CENTER {0} \
  CONFIG.PSU__DDRC__ROW_ADDR_COUNT {16} \
  CONFIG.PSU__DDRC__SB_TARGET {<Select>} \
  CONFIG.PSU__DDRC__SELF_REF_ABORT {0} \
  CONFIG.PSU__DDRC__SPEED_BIN {DDR4_2400T} \
  CONFIG.PSU__DDRC__STATIC_RD_MODE {0} \
  CONFIG.PSU__DDRC__TRAIN_DATA_EYE {1} \
  CONFIG.PSU__DDRC__TRAIN_READ_GATE {1} \
  CONFIG.PSU__DDRC__TRAIN_WRITE_LEVEL {1} \
  CONFIG.PSU__DDRC__T_FAW {30.0} \
  CONFIG.PSU__DDRC__T_RAS_MIN {32.0} \
  CONFIG.PSU__DDRC__T_RC {46.16} \
  CONFIG.PSU__DDRC__T_RCD {17} \
  CONFIG.PSU__DDRC__T_RP {17} \
  CONFIG.PSU__DDRC__VIDEO_BUFFER_SIZE {0} \
  CONFIG.PSU__DDRC__VREF {1} \
  CONFIG.PSU__DDR_HIGH_ADDRESS_GUI_ENABLE {1} \
  CONFIG.PSU__DDR_QOS_ENABLE {0} \
  CONFIG.PSU__DDR_QOS_HP0_RDQOS {} \
  CONFIG.PSU__DDR_QOS_HP0_WRQOS {} \
  CONFIG.PSU__DDR_QOS_HP1_RDQOS {} \
  CONFIG.PSU__DDR_QOS_HP1_WRQOS {} \
  CONFIG.PSU__DDR_QOS_HP2_RDQOS {} \
  CONFIG.PSU__DDR_QOS_HP2_WRQOS {} \
  CONFIG.PSU__DDR_QOS_HP3_RDQOS {} \
  CONFIG.PSU__DDR_QOS_HP3_WRQOS {} \
  CONFIG.PSU__DDR_SW_REFRESH_ENABLED {1} \
  CONFIG.PSU__DDR__INTERFACE__FREQMHZ {600.000} \
  CONFIG.PSU__DLL__ISUSED {1} \
  CONFIG.PSU__ENET2__FIFO__ENABLE {0} \
  CONFIG.PSU__ENET2__GRP_MDIO__ENABLE {1} \
  CONFIG.PSU__ENET2__GRP_MDIO__IO {MIO 76 .. 77} \
  CONFIG.PSU__ENET2__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__ENET2__PERIPHERAL__IO {MIO 52 .. 63} \
  CONFIG.PSU__ENET2__PTP__ENABLE {0} \
  CONFIG.PSU__ENET2__TSU__ENABLE {0} \
  CONFIG.PSU__FPDMASTERS_COHERENCY {0} \
  CONFIG.PSU__GEM2_COHERENCY {0} \
  CONFIG.PSU__GEM2_ROUTE_THROUGH_FPD {0} \
  CONFIG.PSU__GEM__TSU__ENABLE {0} \
  CONFIG.PSU__I2C1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__I2C1__PERIPHERAL__IO {MIO 24 .. 25} \
  CONFIG.PSU__PCIE__BAR0_ENABLE {0} \
  CONFIG.PSU__PCIE__BAR0_VAL {0x0} \
  CONFIG.PSU__PCIE__BAR1_ENABLE {0} \
  CONFIG.PSU__PCIE__BAR1_VAL {0x0} \
  CONFIG.PSU__PCIE__BAR2_VAL {0x0} \
  CONFIG.PSU__PCIE__BAR3_VAL {0x0} \
  CONFIG.PSU__PCIE__BAR4_VAL {0x0} \
  CONFIG.PSU__PCIE__BAR5_VAL {0x0} \
  CONFIG.PSU__PCIE__CLASS_CODE_BASE {0x06} \
  CONFIG.PSU__PCIE__CLASS_CODE_INTERFACE {0x0} \
  CONFIG.PSU__PCIE__CLASS_CODE_SUB {0x04} \
  CONFIG.PSU__PCIE__CLASS_CODE_VALUE {0x60400} \
  CONFIG.PSU__PCIE__CRS_SW_VISIBILITY {1} \
  CONFIG.PSU__PCIE__DEVICE_ID {0xD011} \
  CONFIG.PSU__PCIE__DEVICE_PORT_TYPE {Root Port} \
  CONFIG.PSU__PCIE__EROM_ENABLE {0} \
  CONFIG.PSU__PCIE__EROM_VAL {0x0} \
  CONFIG.PSU__PCIE__INTX_GENERATION {1} \
  CONFIG.PSU__PCIE__LANE0__ENABLE {1} \
  CONFIG.PSU__PCIE__LANE0__IO {GT Lane0} \
  CONFIG.PSU__PCIE__LANE1__ENABLE {1} \
  CONFIG.PSU__PCIE__LANE1__IO {GT Lane1} \
  CONFIG.PSU__PCIE__LANE2__ENABLE {1} \
  CONFIG.PSU__PCIE__LANE2__IO {GT Lane2} \
  CONFIG.PSU__PCIE__LANE3__ENABLE {1} \
  CONFIG.PSU__PCIE__LANE3__IO {GT Lane3} \
  CONFIG.PSU__PCIE__LINK_SPEED {5.0 Gb/s} \
  CONFIG.PSU__PCIE__MAXIMUM_LINK_WIDTH {x4} \
  CONFIG.PSU__PCIE__MAX_PAYLOAD_SIZE {256 bytes} \
  CONFIG.PSU__PCIE__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__PCIE__PERIPHERAL__ENDPOINT_ENABLE {0} \
  CONFIG.PSU__PCIE__PERIPHERAL__ROOTPORT_ENABLE {1} \
  CONFIG.PSU__PCIE__PERIPHERAL__ROOTPORT_IO {MIO 31} \
  CONFIG.PSU__PCIE__REF_CLK_FREQ {100} \
  CONFIG.PSU__PCIE__REF_CLK_SEL {Ref Clk0} \
  CONFIG.PSU__PCIE__RESET__POLARITY {Active High} \
  CONFIG.PSU__PCIE__REVISION_ID {0x0} \
  CONFIG.PSU__PCIE__SUBSYSTEM_ID {0x7} \
  CONFIG.PSU__PCIE__SUBSYSTEM_VENDOR_ID {0x10EE} \
  CONFIG.PSU__PCIE__VENDOR_ID {0x10EE} \
  CONFIG.PSU__PROTECTION__MASTERS {USB1:NonSecure;1|USB0:NonSecure;0|S_AXI_LPD:NA;0|S_AXI_HPC1_FPD:NA;0|S_AXI_HPC0_FPD:NA;0|S_AXI_HP3_FPD:NA;0|S_AXI_HP2_FPD:NA;0|S_AXI_HP1_FPD:NA;0|S_AXI_HP0_FPD:NA;0|S_AXI_ACP:NA;0|S_AXI_ACE:NA;0|SD1:NonSecure;1|SD0:NonSecure;1|SATA1:NonSecure;0|SATA0:NonSecure;0|RPU1:Secure;1|RPU0:Secure;1|QSPI:NonSecure;1|PMU:NA;1|PCIe:NonSecure;1|NAND:NonSecure;0|LDMA:NonSecure;1|GPU:NonSecure;1|GEM3:NonSecure;0|GEM2:NonSecure;1|GEM1:NonSecure;0|GEM0:NonSecure;0|FDMA:NonSecure;1|DP:NonSecure;0|DAP:NA;1|Coresight:NA;1|CSU:NA;1|APU:NA;1}\
  CONFIG.PSU__QSPI_COHERENCY {0} \
  CONFIG.PSU__QSPI_ROUTE_THROUGH_FPD {0} \
  CONFIG.PSU__QSPI__GRP_FBCLK__ENABLE {0} \
  CONFIG.PSU__QSPI__PERIPHERAL__DATA_MODE {x4} \
  CONFIG.PSU__QSPI__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__QSPI__PERIPHERAL__IO {MIO 0 .. 12} \
  CONFIG.PSU__QSPI__PERIPHERAL__MODE {Dual Parallel} \
  CONFIG.PSU__SD0_COHERENCY {0} \
  CONFIG.PSU__SD0_ROUTE_THROUGH_FPD {0} \
  CONFIG.PSU__SD0__CLK_200_SDR_OTAP_DLY {0x3} \
  CONFIG.PSU__SD0__CLK_50_DDR_ITAP_DLY {0x12} \
  CONFIG.PSU__SD0__CLK_50_DDR_OTAP_DLY {0x6} \
  CONFIG.PSU__SD0__CLK_50_SDR_ITAP_DLY {0x15} \
  CONFIG.PSU__SD0__CLK_50_SDR_OTAP_DLY {0x6} \
  CONFIG.PSU__SD0__DATA_TRANSFER_MODE {8Bit} \
  CONFIG.PSU__SD0__GRP_POW__ENABLE {1} \
  CONFIG.PSU__SD0__GRP_POW__IO {MIO 23} \
  CONFIG.PSU__SD0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SD0__PERIPHERAL__IO {MIO 13 .. 22} \
  CONFIG.PSU__SD0__RESET__ENABLE {1} \
  CONFIG.PSU__SD0__SLOT_TYPE {eMMC} \
  CONFIG.PSU__SD1_COHERENCY {0} \
  CONFIG.PSU__SD1_ROUTE_THROUGH_FPD {0} \
  CONFIG.PSU__SD1__CLK_50_SDR_ITAP_DLY {0x15} \
  CONFIG.PSU__SD1__CLK_50_SDR_OTAP_DLY {0x5} \
  CONFIG.PSU__SD1__DATA_TRANSFER_MODE {4Bit} \
  CONFIG.PSU__SD1__GRP_CD__ENABLE {1} \
  CONFIG.PSU__SD1__GRP_CD__IO {MIO 45} \
  CONFIG.PSU__SD1__GRP_POW__ENABLE {1} \
  CONFIG.PSU__SD1__GRP_POW__IO {MIO 43} \
  CONFIG.PSU__SD1__GRP_WP__ENABLE {1} \
  CONFIG.PSU__SD1__GRP_WP__IO {MIO 44} \
  CONFIG.PSU__SD1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SD1__PERIPHERAL__IO {MIO 46 .. 51} \
  CONFIG.PSU__SD1__SLOT_TYPE {SD 2.0} \
  CONFIG.PSU__SPI0__GRP_SS0__IO {EMIO} \
  CONFIG.PSU__SPI0__GRP_SS1__ENABLE {0} \
  CONFIG.PSU__SPI0__GRP_SS2__ENABLE {0} \
  CONFIG.PSU__SPI0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SPI0__PERIPHERAL__IO {EMIO} \
  CONFIG.PSU__SPI1__GRP_SS0__IO {EMIO} \
  CONFIG.PSU__SPI1__GRP_SS1__ENABLE {1} \
  CONFIG.PSU__SPI1__GRP_SS1__IO {EMIO} \
  CONFIG.PSU__SPI1__GRP_SS2__ENABLE {1} \
  CONFIG.PSU__SPI1__GRP_SS2__IO {EMIO} \
  CONFIG.PSU__SPI1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SPI1__PERIPHERAL__IO {EMIO} \
  CONFIG.PSU__TSU__BUFG_PORT_PAIR {0} \
  CONFIG.PSU__UART0__BAUD_RATE {115200} \
  CONFIG.PSU__UART0__MODEM__ENABLE {0} \
  CONFIG.PSU__UART0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__UART0__PERIPHERAL__IO {MIO 34 .. 35} \
  CONFIG.PSU__USB1_COHERENCY {0} \
  CONFIG.PSU__USB1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__USB1__PERIPHERAL__IO {MIO 64 .. 75} \
  CONFIG.PSU__USB2_1__EMIO__ENABLE {0} \
  CONFIG.PSU__USB3_1__PERIPHERAL__ENABLE {0} \
  CONFIG.PSU__USB__RESET__MODE {Disable} \
  CONFIG.PSU__USE__IRQ0 {0} \
  CONFIG.PSU__USE__M_AXI_GP2 {0} \
  CONFIG.SUBPRESET1 {Custom} \
] [get_bd_cells mpsoc]
